theme: jekyll-theme-cayman
title: AI-based-Car-Recommender-System
description: This is a web-based application that can give a recommendation about estimated car price by inferencing its specifications.
